# Author: Ritik Shah

"""HyperBench: synthetic benchmarking for hyperspectral super-resolution."""

from .__about__ import __version__

from .adapters import (
    BaseAdapter,
    CallableAdapter,
    PipelineAdapter,
    ReconstructionInputs,
    TensorFlowModelAdapter,
    TorchModelAdapter,
)
from .benchmark import (
    BenchmarkCase,
    BenchmarkConfig,
    BenchmarkResults,
    DegradationSpec,
    SyntheticCase,
    generate_cases,
    run_benchmark,
)
from .config import benchmark_config_from_dict, load_benchmark_config
from .degradations import (
    AVAILABLE_PSFS,
    SUPPORTED_SRF_BAND_COUNTS,
    make_psf,
    normalize_image,
    spatial_degradation,
    spectral_degradation,
)
from .exceptions import (
    AdapterError,
    AdapterOutputError,
    ConfigurationError,
    FrameworkAvailabilityError,
    HyperBenchError,
    IOValidationError,
    MetricsError,
    PipelineError,
    SceneKeyError,
    ShapeMismatchError,
    UnsupportedPSFError,
    UnsupportedSRFError,
)
from .io import load_hsi
from .metrics import (
    AVAILABLE_METRICS,
    DEFAULT_METRICS,
    compute_ergas,
    compute_psnr,
    compute_rmse,
    compute_sam,
    compute_ssim,
    compute_uiqi,
    evaluate_metrics,
)
from .types import Array, Metadata, PathLike
from .utils import (
    convert_prediction_to_numpy_hwc,
    get_preferred_tensorflow_device,
    get_preferred_torch_device,
    get_tensorflow_device_info,
    get_torch_device_info,
    is_tensorflow_available,
    is_torch_available,
    numpy_hwc_to_tf_image,
    numpy_hwc_to_torch_image,
    numpy_prediction_to_hwc,
    numpy_to_tf_matrix,
    numpy_to_torch_matrix,
    plot_spectra,
    print_data_stats,
    print_framework_device_summary,
    tf_image_to_numpy_hwc,
    tf_matrix_to_numpy,
    torch_image_to_numpy_hwc,
    torch_matrix_to_numpy,
    visualize_band,
    visualize_hsi,
    visualize_multispectral_with_srf,
    visualize_psfs,
)

__all__ = [
    "__version__",
    "Array",
    "PathLike",
    "Metadata",
    "HyperBenchError",
    "ConfigurationError",
    "IOValidationError",
    "SceneKeyError",
    "ShapeMismatchError",
    "UnsupportedPSFError",
    "UnsupportedSRFError",
    "AdapterError",
    "AdapterOutputError",
    "PipelineError",
    "MetricsError",
    "FrameworkAvailabilityError",
    "BaseAdapter",
    "CallableAdapter",
    "PipelineAdapter",
    "TorchModelAdapter",
    "TensorFlowModelAdapter",
    "ReconstructionInputs",
    "DegradationSpec",
    "BenchmarkConfig",
    "BenchmarkCase",
    "SyntheticCase",
    "BenchmarkResults",
    "generate_cases",
    "run_benchmark",
    "benchmark_config_from_dict",
    "load_benchmark_config",
    "load_hsi",
    "AVAILABLE_PSFS",
    "SUPPORTED_SRF_BAND_COUNTS",
    "make_psf",
    "normalize_image",
    "spatial_degradation",
    "spectral_degradation",
    "AVAILABLE_METRICS",
    "DEFAULT_METRICS",
    "compute_rmse",
    "compute_psnr",
    "compute_ssim",
    "compute_uiqi",
    "compute_ergas",
    "compute_sam",
    "evaluate_metrics",
    "print_data_stats",
    "visualize_hsi",
    "visualize_band",
    "visualize_multispectral_with_srf",
    "plot_spectra",
    "visualize_psfs",
    "is_torch_available",
    "is_tensorflow_available",
    "get_torch_device_info",
    "get_tensorflow_device_info",
    "get_preferred_torch_device",
    "get_preferred_tensorflow_device",
    "print_framework_device_summary",
    "numpy_hwc_to_tf_image",
    "tf_image_to_numpy_hwc",
    "numpy_to_tf_matrix",
    "tf_matrix_to_numpy",
    "numpy_hwc_to_torch_image",
    "torch_image_to_numpy_hwc",
    "numpy_to_torch_matrix",
    "torch_matrix_to_numpy",
    "numpy_prediction_to_hwc",
    "convert_prediction_to_numpy_hwc",
]