# Author: Ritik Shah

"""Shared utility helpers for HyperBench."""

from .frameworks import (
    convert_prediction_to_numpy_hwc,
    get_preferred_tensorflow_device,
    get_preferred_torch_device,
    get_tensorflow_device_info,
    get_torch_device_info,
    is_tensorflow_available,
    is_torch_available,
    numpy_hwc_to_tf_image,
    numpy_hwc_to_torch_image,
    numpy_prediction_to_hwc,
    numpy_to_tf_matrix,
    numpy_to_torch_matrix,
    print_framework_device_summary,
    tf_image_to_numpy_hwc,
    tf_matrix_to_numpy,
    torch_image_to_numpy_hwc,
    torch_matrix_to_numpy,
)
from .logging import (
    configure_logger,
    get_logger,
    log_benchmark_start,
    log_case_failure,
    log_case_start,
    log_case_success,
)
from .random import make_rng, set_random_seed
from .validation import (
    ensure_channel_last_hsi,
    validate_band_count,
    validate_custom_srf,
    validate_downsample_ratio,
    validate_experiment_inputs,
    validate_prediction_shape,
    validate_scene_size_for_ratio,
)
from .visualization import (
    plot_spectra,
    print_data_stats,
    visualize_band,
    visualize_hsi,
    visualize_multispectral_with_srf,
    visualize_psfs,
)

__all__ = [
    "is_torch_available",
    "is_tensorflow_available",
    "get_torch_device_info",
    "get_tensorflow_device_info",
    "get_preferred_torch_device",
    "get_preferred_tensorflow_device",
    "print_framework_device_summary",
    "numpy_hwc_to_tf_image",
    "tf_image_to_numpy_hwc",
    "numpy_to_tf_matrix",
    "tf_matrix_to_numpy",
    "numpy_hwc_to_torch_image",
    "torch_image_to_numpy_hwc",
    "numpy_to_torch_matrix",
    "torch_matrix_to_numpy",
    "numpy_prediction_to_hwc",
    "convert_prediction_to_numpy_hwc",
    "configure_logger",
    "get_logger",
    "log_benchmark_start",
    "log_case_start",
    "log_case_success",
    "log_case_failure",
    "set_random_seed",
    "make_rng",
    "ensure_channel_last_hsi",
    "validate_prediction_shape",
    "validate_downsample_ratio",
    "validate_scene_size_for_ratio",
    "validate_band_count",
    "validate_custom_srf",
    "validate_experiment_inputs",
    "print_data_stats",
    "visualize_hsi",
    "visualize_band",
    "visualize_multispectral_with_srf",
    "plot_spectra",
    "visualize_psfs",
]